#!/bin/bash
## ---------------------------------------
## A simple script to list running jobs
## in SLURM system.
## 
## Platform: WHU_hpc with SLURM
## Author  : Kaixiang Huang
## ---------------------------------------

/usr/bin/squeue -o '%.8A %.9P %.13j %.2t %.12M %.5D %.4C %R' $@ |\
    awk '{
        if(NR==1)
            printf "%11s %9s      JOBNAME STATUS %10s %5s %4s %s\n", \
                $1,$2,$5,$6,$7,$8;
        else
            printf "%12s  %-6s %13s   %-2s %12s %3s   %3s  %-s\n", \
                $1,$2,$3,$4,$5,$6,$7,$8;
        fi
    }'

printf "\n    USE squeuep TO SEE ABSOLUTE PATH FOR EACH JOB.\n\
    USE sidle TO SEE AVAILABLE NODES AND CPUS.\n"
